CREATE TABLE BOOK
(
    ID          SERIAL PRIMARY KEY,
    NAME        VARCHAR(50),
    WRITER      VARCHAR(50),
    DESCRIPTION VARCHAR(100)
);

CREATE

    INDEX IDX_BOOK_FBI ON BOOK (ID);

COMMIT;